### PR TITLE
Support for chef-solo workflow?

### PR DESCRIPTION
**Pull request by j-rivero**
Some configurations I needed for local development and execution of `chef-solo`. Documented in the README.

@nuclearsandwich not sure if there is a better/easier workflow.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I think for most standalone cookbooks like this our deployment strategy should be built into our internal chef repository.

**Comment by j-rivero** [comment]
> I think for most standalone cookbooks like this our deployment strategy should be built into our internal chef repository.

Agree. This PR and the implementation of the solo mechanism was more designed to make development of this cookbook easier.

**Comment by nuclearsandwich** [comment]
> This PR and the implementation of the solo mechanism was more designed to make development of this cookbook easier.

Would it make sense to do development entirely within test kitchen and use its facilities for running chef rather than using chef solo directly an independently managed target machine?


My current feeling is that these standalone chef-solo configs are extra weight we don't need to carry since kitchen-ci includes configuration not just for managing how chef should be run but for the environment in which they run which takes a huge burden off of contribution (at the very real cost of a heavyweight dependency on chef-workstation and virtualbox).

**Comment by j-rivero** [comment]
> Would it make sense to do development entirely within test kitchen and use its facilities for running chef rather than using chef solo directly an independently managed target machine?

I might be wrong about kitchen capacities. Can it be run on a bare-metal host directly? My use case with this PR was: I spawned an AWS machine and use chef-solo to run, test, fix this code until it worked.

**Comment by nuclearsandwich** [comment]
> I might be wrong about kitchen capacities. Can it be run on a bare-metal host directly? My use case with this PR was: I spawned an AWS machine and use chef-solo to run, test, fix this code until it worked.

Kitchen has a number of drivers. I've been using the Vagrant/virtualbox driver which is the default and that gives me the ability to shell into the machine to iterate and debug with `kitchen login`. It's also usable with an EC2 driver that uses your local AWS EC2 credentials if you have them. I haven't found a stable Qemu/KVM or LXD driver although I've experimented with them. The dokken driver is apparently usable directly on ubuntu-latest (which is currently ubuntu-18.04).

**Pull request closed without merging**
